//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileDesktop.ServicePhieuNhap {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class PhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.CT_PhieuNhap[] CT_PhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNPPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaPNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.NhaPhanPhoi NhaPhanPhoiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.NhanVien NhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TrigiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.CT_PhieuNhap[] CT_PhieuNhap {
            get {
                return this.CT_PhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.CT_PhieuNhapField, value) != true)) {
                    this.CT_PhieuNhapField = value;
                    this.RaisePropertyChanged("CT_PhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNPP {
            get {
                return this.MaNPPField;
            }
            set {
                if ((this.MaNPPField.Equals(value) != true)) {
                    this.MaNPPField = value;
                    this.RaisePropertyChanged("MaNPP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaPN {
            get {
                return this.MaPNField;
            }
            set {
                if ((this.MaPNField.Equals(value) != true)) {
                    this.MaPNField = value;
                    this.RaisePropertyChanged("MaPN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Ngay {
            get {
                return this.NgayField;
            }
            set {
                if ((this.NgayField.Equals(value) != true)) {
                    this.NgayField = value;
                    this.RaisePropertyChanged("Ngay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.NhaPhanPhoi NhaPhanPhoi {
            get {
                return this.NhaPhanPhoiField;
            }
            set {
                if ((object.ReferenceEquals(this.NhaPhanPhoiField, value) != true)) {
                    this.NhaPhanPhoiField = value;
                    this.RaisePropertyChanged("NhaPhanPhoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.NhanVien NhanVien {
            get {
                return this.NhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.NhanVienField, value) != true)) {
                    this.NhanVienField = value;
                    this.RaisePropertyChanged("NhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Trigia {
            get {
                return this.TrigiaField;
            }
            set {
                if ((this.TrigiaField.Equals(value) != true)) {
                    this.TrigiaField = value;
                    this.RaisePropertyChanged("Trigia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhaPhanPhoi", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class NhaPhanPhoi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNPPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.PhieuNhap[] PhieuNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoDTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNPPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNPP {
            get {
                return this.MaNPPField;
            }
            set {
                if ((this.MaNPPField.Equals(value) != true)) {
                    this.MaNPPField = value;
                    this.RaisePropertyChanged("MaNPP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.PhieuNhap[] PhieuNhaps {
            get {
                return this.PhieuNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieuNhapsField, value) != true)) {
                    this.PhieuNhapsField = value;
                    this.RaisePropertyChanged("PhieuNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SoDT {
            get {
                return this.SoDTField;
            }
            set {
                if ((object.ReferenceEquals(this.SoDTField, value) != true)) {
                    this.SoDTField = value;
                    this.RaisePropertyChanged("SoDT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNPP {
            get {
                return this.TenNPPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNPPField, value) != true)) {
                    this.TenNPPField = value;
                    this.RaisePropertyChanged("TenNPP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhanVien", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class NhanVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.DonHang[] DonHangsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.PhieuNhap[] PhieuNhapsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuyenNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.QuyenNhanVien QuyenNhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.DonHang[] DonHangs {
            get {
                return this.DonHangsField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangsField, value) != true)) {
                    this.DonHangsField = value;
                    this.RaisePropertyChanged("DonHangs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.PhieuNhap[] PhieuNhaps {
            get {
                return this.PhieuNhapsField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieuNhapsField, value) != true)) {
                    this.PhieuNhapsField = value;
                    this.RaisePropertyChanged("PhieuNhaps");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuyenNV {
            get {
                return this.QuyenNVField;
            }
            set {
                if ((this.QuyenNVField.Equals(value) != true)) {
                    this.QuyenNVField = value;
                    this.RaisePropertyChanged("QuyenNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.QuyenNhanVien QuyenNhanVien {
            get {
                return this.QuyenNhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.QuyenNhanVienField, value) != true)) {
                    this.QuyenNhanVienField = value;
                    this.RaisePropertyChanged("QuyenNhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNV {
            get {
                return this.TenNVField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNVField, value) != true)) {
                    this.TenNVField = value;
                    this.RaisePropertyChanged("TenNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CT_PhieuNhap", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class CT_PhieuNhap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaPNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.PhieuNhap PhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaPN {
            get {
                return this.MaPNField;
            }
            set {
                if ((this.MaPNField.Equals(value) != true)) {
                    this.MaPNField = value;
                    this.RaisePropertyChanged("MaPN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.PhieuNhap PhieuNhap {
            get {
                return this.PhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.PhieuNhapField, value) != true)) {
                    this.PhieuNhapField = value;
                    this.RaisePropertyChanged("PhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanPham", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.CT_DonHang[] CT_DonHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.CT_PhieuNhap[] CT_PhieuNhapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNSXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MoTaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.NhaSanXuat NhaSanXuatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlHinhField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.CT_DonHang[] CT_DonHang {
            get {
                return this.CT_DonHangField;
            }
            set {
                if ((object.ReferenceEquals(this.CT_DonHangField, value) != true)) {
                    this.CT_DonHangField = value;
                    this.RaisePropertyChanged("CT_DonHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.CT_PhieuNhap[] CT_PhieuNhap {
            get {
                return this.CT_PhieuNhapField;
            }
            set {
                if ((object.ReferenceEquals(this.CT_PhieuNhapField, value) != true)) {
                    this.CT_PhieuNhapField = value;
                    this.RaisePropertyChanged("CT_PhieuNhap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNSX {
            get {
                return this.MaNSXField;
            }
            set {
                if ((this.MaNSXField.Equals(value) != true)) {
                    this.MaNSXField = value;
                    this.RaisePropertyChanged("MaNSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MoTa {
            get {
                return this.MoTaField;
            }
            set {
                if ((object.ReferenceEquals(this.MoTaField, value) != true)) {
                    this.MoTaField = value;
                    this.RaisePropertyChanged("MoTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.NhaSanXuat NhaSanXuat {
            get {
                return this.NhaSanXuatField;
            }
            set {
                if ((object.ReferenceEquals(this.NhaSanXuatField, value) != true)) {
                    this.NhaSanXuatField = value;
                    this.RaisePropertyChanged("NhaSanXuat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlHinh {
            get {
                return this.UrlHinhField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlHinhField, value) != true)) {
                    this.UrlHinhField = value;
                    this.RaisePropertyChanged("UrlHinh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NhaSanXuat", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class NhaSanXuat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNSXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.SanPham[] SanPhamsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNSXField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNSX {
            get {
                return this.MaNSXField;
            }
            set {
                if ((this.MaNSXField.Equals(value) != true)) {
                    this.MaNSXField = value;
                    this.RaisePropertyChanged("MaNSX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.SanPham[] SanPhams {
            get {
                return this.SanPhamsField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamsField, value) != true)) {
                    this.SanPhamsField = value;
                    this.RaisePropertyChanged("SanPhams");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNSX {
            get {
                return this.TenNSXField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNSXField, value) != true)) {
                    this.TenNSXField = value;
                    this.RaisePropertyChanged("TenNSX");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CT_DonHang", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class CT_DonHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.DonHang DonHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.SanPham SanPhamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SoLuongField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.DonHang DonHang {
            get {
                return this.DonHangField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangField, value) != true)) {
                    this.DonHangField = value;
                    this.RaisePropertyChanged("DonHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((this.MaDHField.Equals(value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.SanPham SanPham {
            get {
                return this.SanPhamField;
            }
            set {
                if ((object.ReferenceEquals(this.SanPhamField, value) != true)) {
                    this.SanPhamField = value;
                    this.RaisePropertyChanged("SanPham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DonHang", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class DonHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.CT_DonHang[] CT_DonHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.KhachHang KhachHangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaNVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.NhanVien NhanVienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TinhTrangField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TrigiaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.CT_DonHang[] CT_DonHang {
            get {
                return this.CT_DonHangField;
            }
            set {
                if ((object.ReferenceEquals(this.CT_DonHangField, value) != true)) {
                    this.CT_DonHangField = value;
                    this.RaisePropertyChanged("CT_DonHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.KhachHang KhachHang {
            get {
                return this.KhachHangField;
            }
            set {
                if ((object.ReferenceEquals(this.KhachHangField, value) != true)) {
                    this.KhachHangField = value;
                    this.RaisePropertyChanged("KhachHang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDH {
            get {
                return this.MaDHField;
            }
            set {
                if ((this.MaDHField.Equals(value) != true)) {
                    this.MaDHField = value;
                    this.RaisePropertyChanged("MaDH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaNV {
            get {
                return this.MaNVField;
            }
            set {
                if ((this.MaNVField.Equals(value) != true)) {
                    this.MaNVField = value;
                    this.RaisePropertyChanged("MaNV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Ngay {
            get {
                return this.NgayField;
            }
            set {
                if ((this.NgayField.Equals(value) != true)) {
                    this.NgayField = value;
                    this.RaisePropertyChanged("Ngay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.NhanVien NhanVien {
            get {
                return this.NhanVienField;
            }
            set {
                if ((object.ReferenceEquals(this.NhanVienField, value) != true)) {
                    this.NhanVienField = value;
                    this.RaisePropertyChanged("NhanVien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TinhTrang {
            get {
                return this.TinhTrangField;
            }
            set {
                if ((this.TinhTrangField.Equals(value) != true)) {
                    this.TinhTrangField = value;
                    this.RaisePropertyChanged("TinhTrang");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Trigia {
            get {
                return this.TrigiaField;
            }
            set {
                if ((this.TrigiaField.Equals(value) != true)) {
                    this.TrigiaField = value;
                    this.RaisePropertyChanged("Trigia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHang", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class KhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaChiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DienThoaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.DonHang[] DonHangsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GioiTinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HoTenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> NgaySinhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaChi {
            get {
                return this.DiaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaChiField, value) != true)) {
                    this.DiaChiField = value;
                    this.RaisePropertyChanged("DiaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DienThoai {
            get {
                return this.DienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.DienThoaiField, value) != true)) {
                    this.DienThoaiField = value;
                    this.RaisePropertyChanged("DienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.DonHang[] DonHangs {
            get {
                return this.DonHangsField;
            }
            set {
                if ((object.ReferenceEquals(this.DonHangsField, value) != true)) {
                    this.DonHangsField = value;
                    this.RaisePropertyChanged("DonHangs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GioiTinh {
            get {
                return this.GioiTinhField;
            }
            set {
                if ((object.ReferenceEquals(this.GioiTinhField, value) != true)) {
                    this.GioiTinhField = value;
                    this.RaisePropertyChanged("GioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HoTen {
            get {
                return this.HoTenField;
            }
            set {
                if ((object.ReferenceEquals(this.HoTenField, value) != true)) {
                    this.HoTenField = value;
                    this.RaisePropertyChanged("HoTen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaKH {
            get {
                return this.MaKHField;
            }
            set {
                if ((this.MaKHField.Equals(value) != true)) {
                    this.MaKHField = value;
                    this.RaisePropertyChanged("MaKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> NgaySinh {
            get {
                return this.NgaySinhField;
            }
            set {
                if ((this.NgaySinhField.Equals(value) != true)) {
                    this.NgaySinhField = value;
                    this.RaisePropertyChanged("NgaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuyenNhanVien", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class QuyenNhanVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaQField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MobileDesktop.ServicePhieuNhap.NhanVien[] NhanViensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenQField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaQ {
            get {
                return this.MaQField;
            }
            set {
                if ((this.MaQField.Equals(value) != true)) {
                    this.MaQField = value;
                    this.RaisePropertyChanged("MaQ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MobileDesktop.ServicePhieuNhap.NhanVien[] NhanViens {
            get {
                return this.NhanViensField;
            }
            set {
                if ((object.ReferenceEquals(this.NhanViensField, value) != true)) {
                    this.NhanViensField = value;
                    this.RaisePropertyChanged("NhanViens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenQ {
            get {
                return this.TenQField;
            }
            set {
                if ((object.ReferenceEquals(this.TenQField, value) != true)) {
                    this.TenQField = value;
                    this.RaisePropertyChanged("TenQ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhieuNhap_SanPham", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class PhieuNhap_SanPham : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaPNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaSPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoLuongField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenSPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gia {
            get {
                return this.GiaField;
            }
            set {
                if ((this.GiaField.Equals(value) != true)) {
                    this.GiaField = value;
                    this.RaisePropertyChanged("Gia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaPN {
            get {
                return this.MaPNField;
            }
            set {
                if ((this.MaPNField.Equals(value) != true)) {
                    this.MaPNField = value;
                    this.RaisePropertyChanged("MaPN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaSP {
            get {
                return this.MaSPField;
            }
            set {
                if ((this.MaSPField.Equals(value) != true)) {
                    this.MaSPField = value;
                    this.RaisePropertyChanged("MaSP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoLuong {
            get {
                return this.SoLuongField;
            }
            set {
                if ((this.SoLuongField.Equals(value) != true)) {
                    this.SoLuongField = value;
                    this.RaisePropertyChanged("SoLuong");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenSP {
            get {
                return this.TenSPField;
            }
            set {
                if ((object.ReferenceEquals(this.TenSPField, value) != true)) {
                    this.TenSPField = value;
                    this.RaisePropertyChanged("TenSP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ThongkePN", Namespace="http://schemas.datacontract.org/2004/07/WcfMobile")]
    [System.SerializableAttribute()]
    public partial class ThongkePN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DONGIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SOLUONGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int THANHTIENField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DONGIA {
            get {
                return this.DONGIAField;
            }
            set {
                if ((this.DONGIAField.Equals(value) != true)) {
                    this.DONGIAField = value;
                    this.RaisePropertyChanged("DONGIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SOLUONG {
            get {
                return this.SOLUONGField;
            }
            set {
                if ((this.SOLUONGField.Equals(value) != true)) {
                    this.SOLUONGField = value;
                    this.RaisePropertyChanged("SOLUONG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEN {
            get {
                return this.TENField;
            }
            set {
                if ((object.ReferenceEquals(this.TENField, value) != true)) {
                    this.TENField = value;
                    this.RaisePropertyChanged("TEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int THANHTIEN {
            get {
                return this.THANHTIENField;
            }
            set {
                if ((this.THANHTIENField.Equals(value) != true)) {
                    this.THANHTIENField = value;
                    this.RaisePropertyChanged("THANHTIEN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePhieuNhap.IServicePhieuNhap")]
    public interface IServicePhieuNhap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/SelectPhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/SelectPhieuNhapResponse")]
        MobileDesktop.ServicePhieuNhap.PhieuNhap[] SelectPhieuNhap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/SelectPhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/SelectPhieuNhapResponse")]
        System.Threading.Tasks.Task<MobileDesktop.ServicePhieuNhap.PhieuNhap[]> SelectPhieuNhapAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/InsertPhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/InsertPhieuNhapResponse")]
        int InsertPhieuNhap(MobileDesktop.ServicePhieuNhap.PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/InsertPhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/InsertPhieuNhapResponse")]
        System.Threading.Tasks.Task<int> InsertPhieuNhapAsync(MobileDesktop.ServicePhieuNhap.PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/UpdatePhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/UpdatePhieuNhapResponse")]
        int UpdatePhieuNhap(MobileDesktop.ServicePhieuNhap.PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/UpdatePhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/UpdatePhieuNhapResponse")]
        System.Threading.Tasks.Task<int> UpdatePhieuNhapAsync(MobileDesktop.ServicePhieuNhap.PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/DeletePhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/DeletePhieuNhapResponse")]
        int DeletePhieuNhap(MobileDesktop.ServicePhieuNhap.PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/DeletePhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/DeletePhieuNhapResponse")]
        System.Threading.Tasks.Task<int> DeletePhieuNhapAsync(MobileDesktop.ServicePhieuNhap.PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/SelectCTPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/SelectCTPNResponse")]
        MobileDesktop.ServicePhieuNhap.CT_PhieuNhap[] SelectCTPN();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/SelectCTPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/SelectCTPNResponse")]
        System.Threading.Tasks.Task<MobileDesktop.ServicePhieuNhap.CT_PhieuNhap[]> SelectCTPNAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/SelectCTPN_ByMaPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/SelectCTPN_ByMaPNResponse")]
        MobileDesktop.ServicePhieuNhap.PhieuNhap_SanPham[] SelectCTPN_ByMaPN(int ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/SelectCTPN_ByMaPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/SelectCTPN_ByMaPNResponse")]
        System.Threading.Tasks.Task<MobileDesktop.ServicePhieuNhap.PhieuNhap_SanPham[]> SelectCTPN_ByMaPNAsync(int ma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/InsertCTPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/InsertCTPNResponse")]
        int InsertCTPN(MobileDesktop.ServicePhieuNhap.CT_PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/InsertCTPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/InsertCTPNResponse")]
        System.Threading.Tasks.Task<int> InsertCTPNAsync(MobileDesktop.ServicePhieuNhap.CT_PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/UpdateCTPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/UpdateCTPNResponse")]
        int UpdateCTPN(MobileDesktop.ServicePhieuNhap.CT_PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/UpdateCTPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/UpdateCTPNResponse")]
        System.Threading.Tasks.Task<int> UpdateCTPNAsync(MobileDesktop.ServicePhieuNhap.CT_PhieuNhap info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/DeleteCTPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/DeleteCTPNResponse")]
        int DeleteCTPN(int mapn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/DeleteCTPN", ReplyAction="http://tempuri.org/IServicePhieuNhap/DeleteCTPNResponse")]
        System.Threading.Tasks.Task<int> DeleteCTPNAsync(int mapn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/GetNewIDPhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/GetNewIDPhieuNhapResponse")]
        int GetNewIDPhieuNhap();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/GetNewIDPhieuNhap", ReplyAction="http://tempuri.org/IServicePhieuNhap/GetNewIDPhieuNhapResponse")]
        System.Threading.Tasks.Task<int> GetNewIDPhieuNhapAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/UpdateSoLuongSanPham", ReplyAction="http://tempuri.org/IServicePhieuNhap/UpdateSoLuongSanPhamResponse")]
        int UpdateSoLuongSanPham(int masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/UpdateSoLuongSanPham", ReplyAction="http://tempuri.org/IServicePhieuNhap/UpdateSoLuongSanPhamResponse")]
        System.Threading.Tasks.Task<int> UpdateSoLuongSanPhamAsync(int masp, int soluong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/ThongkeSPNhapThang", ReplyAction="http://tempuri.org/IServicePhieuNhap/ThongkeSPNhapThangResponse")]
        MobileDesktop.ServicePhieuNhap.ThongkePN[] ThongkeSPNhapThang(int thang, int nam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePhieuNhap/ThongkeSPNhapThang", ReplyAction="http://tempuri.org/IServicePhieuNhap/ThongkeSPNhapThangResponse")]
        System.Threading.Tasks.Task<MobileDesktop.ServicePhieuNhap.ThongkePN[]> ThongkeSPNhapThangAsync(int thang, int nam);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePhieuNhapChannel : MobileDesktop.ServicePhieuNhap.IServicePhieuNhap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePhieuNhapClient : System.ServiceModel.ClientBase<MobileDesktop.ServicePhieuNhap.IServicePhieuNhap>, MobileDesktop.ServicePhieuNhap.IServicePhieuNhap {
        
        public ServicePhieuNhapClient() {
        }
        
        public ServicePhieuNhapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePhieuNhapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePhieuNhapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePhieuNhapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MobileDesktop.ServicePhieuNhap.PhieuNhap[] SelectPhieuNhap() {
            return base.Channel.SelectPhieuNhap();
        }
        
        public System.Threading.Tasks.Task<MobileDesktop.ServicePhieuNhap.PhieuNhap[]> SelectPhieuNhapAsync() {
            return base.Channel.SelectPhieuNhapAsync();
        }
        
        public int InsertPhieuNhap(MobileDesktop.ServicePhieuNhap.PhieuNhap info) {
            return base.Channel.InsertPhieuNhap(info);
        }
        
        public System.Threading.Tasks.Task<int> InsertPhieuNhapAsync(MobileDesktop.ServicePhieuNhap.PhieuNhap info) {
            return base.Channel.InsertPhieuNhapAsync(info);
        }
        
        public int UpdatePhieuNhap(MobileDesktop.ServicePhieuNhap.PhieuNhap info) {
            return base.Channel.UpdatePhieuNhap(info);
        }
        
        public System.Threading.Tasks.Task<int> UpdatePhieuNhapAsync(MobileDesktop.ServicePhieuNhap.PhieuNhap info) {
            return base.Channel.UpdatePhieuNhapAsync(info);
        }
        
        public int DeletePhieuNhap(MobileDesktop.ServicePhieuNhap.PhieuNhap info) {
            return base.Channel.DeletePhieuNhap(info);
        }
        
        public System.Threading.Tasks.Task<int> DeletePhieuNhapAsync(MobileDesktop.ServicePhieuNhap.PhieuNhap info) {
            return base.Channel.DeletePhieuNhapAsync(info);
        }
        
        public MobileDesktop.ServicePhieuNhap.CT_PhieuNhap[] SelectCTPN() {
            return base.Channel.SelectCTPN();
        }
        
        public System.Threading.Tasks.Task<MobileDesktop.ServicePhieuNhap.CT_PhieuNhap[]> SelectCTPNAsync() {
            return base.Channel.SelectCTPNAsync();
        }
        
        public MobileDesktop.ServicePhieuNhap.PhieuNhap_SanPham[] SelectCTPN_ByMaPN(int ma) {
            return base.Channel.SelectCTPN_ByMaPN(ma);
        }
        
        public System.Threading.Tasks.Task<MobileDesktop.ServicePhieuNhap.PhieuNhap_SanPham[]> SelectCTPN_ByMaPNAsync(int ma) {
            return base.Channel.SelectCTPN_ByMaPNAsync(ma);
        }
        
        public int InsertCTPN(MobileDesktop.ServicePhieuNhap.CT_PhieuNhap info) {
            return base.Channel.InsertCTPN(info);
        }
        
        public System.Threading.Tasks.Task<int> InsertCTPNAsync(MobileDesktop.ServicePhieuNhap.CT_PhieuNhap info) {
            return base.Channel.InsertCTPNAsync(info);
        }
        
        public int UpdateCTPN(MobileDesktop.ServicePhieuNhap.CT_PhieuNhap info) {
            return base.Channel.UpdateCTPN(info);
        }
        
        public System.Threading.Tasks.Task<int> UpdateCTPNAsync(MobileDesktop.ServicePhieuNhap.CT_PhieuNhap info) {
            return base.Channel.UpdateCTPNAsync(info);
        }
        
        public int DeleteCTPN(int mapn) {
            return base.Channel.DeleteCTPN(mapn);
        }
        
        public System.Threading.Tasks.Task<int> DeleteCTPNAsync(int mapn) {
            return base.Channel.DeleteCTPNAsync(mapn);
        }
        
        public int GetNewIDPhieuNhap() {
            return base.Channel.GetNewIDPhieuNhap();
        }
        
        public System.Threading.Tasks.Task<int> GetNewIDPhieuNhapAsync() {
            return base.Channel.GetNewIDPhieuNhapAsync();
        }
        
        public int UpdateSoLuongSanPham(int masp, int soluong) {
            return base.Channel.UpdateSoLuongSanPham(masp, soluong);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSoLuongSanPhamAsync(int masp, int soluong) {
            return base.Channel.UpdateSoLuongSanPhamAsync(masp, soluong);
        }
        
        public MobileDesktop.ServicePhieuNhap.ThongkePN[] ThongkeSPNhapThang(int thang, int nam) {
            return base.Channel.ThongkeSPNhapThang(thang, nam);
        }
        
        public System.Threading.Tasks.Task<MobileDesktop.ServicePhieuNhap.ThongkePN[]> ThongkeSPNhapThangAsync(int thang, int nam) {
            return base.Channel.ThongkeSPNhapThangAsync(thang, nam);
        }
    }
}
