//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaPhanPhoi
    {
        public NhaPhanPhoi()
        {
            this.PhieuNhaps = new HashSet<PhieuNhap>();
        }
    
        public int MaNPP { get; set; }
        public string TenNPP { get; set; }
        public string DiaChi { get; set; }
        public string Email { get; set; }
        public string SoDT { get; set; }
    
        public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; }
    }
}
