//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            this.CT_PhieuNhap = new HashSet<CT_PhieuNhap>();
        }
    
        public int MaPN { get; set; }
        public Nullable<int> MaNPP { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> Trigia { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        public virtual ICollection<CT_PhieuNhap> CT_PhieuNhap { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
    }
}
