//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuyenNhanVien
    {
        public QuyenNhanVien()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int MaQ { get; set; }
        public string TenQ { get; set; }
    
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
