//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMobile
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.CT_DonHang = new HashSet<CT_DonHang>();
            this.CT_PhieuNhap = new HashSet<CT_PhieuNhap>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string UrlHinh { get; set; }
        public int Gia { get; set; }
        public string MoTa { get; set; }
        public int MaNSX { get; set; }
        public int SoLuong { get; set; }
    
        public virtual ICollection<CT_DonHang> CT_DonHang { get; set; }
        public virtual ICollection<CT_PhieuNhap> CT_PhieuNhap { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
    }
}
